### ISSUE TITLE
It would be awsome if you publish any test/example programm in (maybe) another repo.

### ISSUE THREAD

**Issue by ghost** [ilobilo/limine-terminal#1]
It would be awsome if you publish any test/example kernel in (maybe) another repo. Propably something like this already exist for testing use, so it would be even helpfull to publish it in a not working state!  
It would help to understand the implementation, and could make this the first easier to understand method for printing in limine. There is no other simple implementation with direct flanterm. And also not in project like limine-c-template/rust-template. 

Overall it looks like a verry helpfull project!

**Comment by ilobilo** [comment]
Hi! you can take a look at Ilobilix for an example https://github.com/ilobilo/ilobilix/blob/master/kernel%2Fdrivers%2Fterm.cpp
